### ISSUE TITLE
Download link to preprocessed_zhang.h5ad dataset

### ISSUE THREAD

**Issue by hiraksarkar** [theislab/ncem_tutorials#1]
Hi,

Thanks for writing this amazing tool. Can you please provide the link to `preprocessed_zhang.h5ad` that is required to run the tutorial notebook, or, point me to the url of the dataset.

The closest dataset I could get was `count.h5ad` inside https://download.brainimagelibrary.org/cf/1c/cf1c1a431ef8d021/processed_data/ , Please let me know if that's same as the above file. 

Thanks

**Comment by AnnaChristina** [comment]
Hi @hiraksarkar,

thank you for opening an issue. 

I added the [data preparation notebook](https://github.com/theislab/ncem_benchmarks/blob/main/notebooks/data_preparation/data_preparation_merfish_brain.ipynb) needed to create `preprocessed_zhang.h5ad` to the [ncem_benchmarks](https://github.com/theislab/ncem_benchmarks) repository.

We are using the `counts.h5ad` matrix you mentioned (accessable here ftp://download.brainimagelibrary.org:8811/02/26/02265ddb0dae51de/ ) and additionally `cell_metadata.csv` which contains `x` and `y` coordinates and cell type annotation on cell level. `cell_metadata.csv` can be requested from Zhang et al. directly for further analysis. 

Subsequently, we normalized and logp1 transformed the data with scanpy as stated in the notebook.

Happy to help if you encounter any more difficulties!

**Comment by hiraksarkar** [comment]
Hi @AnnaChristina ,

Thanks a lot. Can you please point me to `cell_metadata.csv` file. I could not find it here.

**Comment by Luosanj** [comment]
Hi, 
I am a reader of 'ncem'. I am appreciated by your excellent work. I plan to use this package with CODEX image data. Yet, I failed to load my data referring the above tutorial code. I find there are a lot of prefix like 'zhang','Hartmann' to build a dataloader. I don't know how to choose them. May I request for a help?

![image](https://user-images.githubusercontent.com/46926952/172426587-8774e0ae-70d5-44a3-a24e-002419955a85.png)

**Comment by AnnaChristina** [comment]
Hi @Luosanj,

thanks for raising the issue andyour interest in using ncem!

from your outstream I inspect you are trying to use ncem on one of our predefined datasets right? If I read your message correctly, you want to use ncem on your own data right? 

For this purpose, we designed a custom dataloader which can be called on any AnnData object and you will just need to specify the categorical cell types in `.obs`. 

Could you confirm that a custom dataloader is what you require? or do you want to use ncem with our predefined datasets? 

Thanks and best!

**Comment by Luosanj** [comment]
Hi Anna,
     Thanks a lot for response! I want to use my own CODEX image data with NCEM tool. Where is the 'custom dataloader' that you build? And by the way, CODEX image data hasn't got genes but has protein marker intensity. In this case do you use marker intensity to replace gene expression in linear model and encoder-decoder model for CODEX image data?

Cheers!

**Comment by AnnaChristina** [comment]
Hi @Luosanj,

we recently added an example for our spatial omics workshop. You can find it here:

https://github.com/theislab/spatial_scog_workshop_2022/tree/main/ncem

we tested ncem on CODEX data before by replacing gene expression with protein marker intensity and it worked well. Pleas let me know if you have any issues working with the custom data loader. 

You can directly run the type coupling analysis on a predefined communication radius. If you would like to inspect the optimal communication resolution, we recommend to first run an ablation study over several distances. Happy to elaborate more on this.

**Comment by Luosanj** [comment]
Thanks for answering Anna ! I tried to use the sample code in 'https://github.com/theislab/spatial_scog_workshop_2022/tree/main/ncem' but it fails to run with following error.  Are there any solutions? 
By the way may I request for a sample code for your 'CODEX' image data? It seems data format differs a lot between different spatial data.

![image](https://user-images.githubusercontent.com/46926952/175564147-db9ebc1e-c6f1-4df6-8be0-d59c0b6715bd.png)


Thanks!
Xin

**Comment by Luosanj** [comment]
Hi Anna,
    The former question has been solved. That problem is due to my python version. I run my CODEX image data successfully with your tutorial. Yet, I have a question that when you run your CODEX Image data, did you normalize marker density data into the range between 0 and 1? From my result, the figure of sender receiver effect through edge 'magnitude' is drawn like this. Have you met this issue before ? The figure of sender receiver effect through number of differential genes is normal. 

![image](https://user-images.githubusercontent.com/46926952/175839365-aa16c156-ea6e-4358-b661-b1f82e60c8b7.png)

![image](https://user-images.githubusercontent.com/46926952/175839414-60278923-26fb-47a6-890b-1eb508c8698a.png)

**Comment by AnnaChristina** [comment]
Hi @hiraksarkar,

which version of ncem are you using?

In the most recent `ncem==0.1.4` we return the dataframe used for ploting the circular plot and this might help to understand what is happening for the magnitude. I would assume one interaction has a quite large absolute magnitude and this might be the issue generating the plot shown above.

**Comment by RunyuXia** [comment]
Hi! When I try to apply the sender-receiver analysis to my dataset, I received this error
(350, 10, 14)
(350, 10, 196)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hailey/anaconda3/envs/newenv/lib/python3.8/site-packages/ncem/interpretation/interpreter.py", line 912, in get_sender_receiver_effects
    x_design = np.concatenate([target, interactions.squeeze()], axis=1)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 14 and the array at index 1 has size 196

I was wondering what might be the cause of this problem and how should I fix this?

**Comment by ChengXiHuang** [comment]
Hi,anna，

I have reached out to the original data authors in hopes of obtaining the necessary data（cell_metadata.csv ） for my paper. However, two days have passed, and I have yet to receive a response. As my research is highly dependent on this data, I was wondering if you might be able to share the cell_metadata.csv file with me.

If possible, could you please send it to my email address: [zengmx7@mail2.sysu.edu.cn]?

I truly appreciate your assistance and understanding, and thank you in advance for your help.
