### ISSUE TITLE
concatenate dimension error

### ISSUE THREAD

**Issue by RunyuXia** [theislab/ncem_tutorials#7]
Hi! When I try to apply the sender-receiver analysis to my dataset, I received this error
(350, 10, 14)
(350, 10, 196)
Traceback (most recent call last):
File "", line 1, in
File "/Users/hailey/anaconda3/envs/newenv/lib/python3.8/site-packages/ncem/interpretation/interpreter.py", line 912, in get_sender_receiver_effects
x_design = np.concatenate([target, interactions.squeeze()], axis=1)
File "<array_function internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 14 and the array at index 1 has size 196

I was wondering what might be the cause of this problem and how should I fix this?

**Comment by showvikbiswas** [comment]
I am facing the same issue, except I am trying to follow the tutorial on how to perform sender-receiver analysis provided in the spatial_scog_workshop_2022 repository:

(330, 10, 8)
(330, 10, 64)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[e:\University\4-1\Research\axolotl\data\ncem\tutorial.ipynb] Cell 14 line 1
----> [1](vscode-notebook-cell:/e%3A/University/4-1/Research/axolotl/data/ncem/tutorial.ipynb#X22sZmlsZQ%3D%3D?line=0) ncem.get_sender_receiver_effects()

File [c:\Users\showv\AppData\Local\Programs\Python\Python39\lib\site-packages\ncem\interpretation\interpreter.py:912](file:///C:/Users/showv/AppData/Local/Programs/Python/Python39/lib/site-packages/ncem/interpretation/interpreter.py:912), in InterpreterInteraction.get_sender_receiver_effects(self, params_type, significance_threshold)
    [910](file:///C:/Users/showv/AppData/Local/Programs/Python/Python39/lib/site-packages/ncem/interpretation/interpreter.py:910) print(target.shape)
    [911](file:///C:/Users/showv/AppData/Local/Programs/Python/Python39/lib/site-packages/ncem/interpretation/interpreter.py:911) print(interactions.shape)
--> [912](file:///C:/Users/showv/AppData/Local/Programs/Python/Python39/lib/site-packages/ncem/interpretation/interpreter.py:912) x_design = np.concatenate([target, interactions.squeeze()], axis=1)
    [913](file:///C:/Users/showv/AppData/Local/Programs/Python/Python39/lib/site-packages/ncem/interpretation/interpreter.py:913) ols = ols_fit(x_=x_design, y_=y)
    [914](file:///C:/Users/showv/AppData/Local/Programs/Python/Python39/lib/site-packages/ncem/interpretation/interpreter.py:914) params = ols.squeeze()

File <__array_function__ internals>:180, in concatenate(*args, **kwargs)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 8 and the array at index 1 has size 64

**Comment by ShuangWang1** [comment]
I am using python3.9 and also encountered the same issue when executing interpreter.get_sender_receiver_effects() in the given tutorial code in analysis_tutorial_mibitof_cancer.ipynb--

100%|█████████▉| 6351/6374 [00:53<00:00, 118.57it/s]
using ols parameters.
(6351, 10, 8)
(6351, 10, 64)
{
	"name": "ValueError",
	"message": "all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 8 and the array at index 1 has size 64",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 1
----> 1 interpreter.get_sender_receiver_effects()

File ~/.conda/envs/ncem_env/lib/python3.9/site-packages/ncem/interpretation/interpreter.py:912, in InterpreterInteraction.get_sender_receiver_effects(self, params_type, significance_threshold)
    910 print(target.shape)
    911 print(interactions.shape)
--> 912 x_design = np.concatenate([target, interactions.squeeze()], axis=1)
    913 ols = ols_fit(x_=x_design, y_=y)
    914 params = ols.squeeze()

File <__array_function__ internals>:200, in concatenate(*args, **kwargs)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 8 and the array at index 1 has size 64"
}

**Comment by irenekyeboah** [comment]
> I am using python3.9 and also encountered the same issue when executing interpreter.get_sender_receiver_effects() in the given tutorial code in analysis_tutorial_mibitof_cancer.ipynb--
> 
> 100%|█████████▉| 6351/6374 [00:53<00:00, 118.57it/s] using ols parameters. (6351, 10, 8) (6351, 10, 64) { "name": "ValueError", "message": "all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 8 and the array at index 1 has size 64", "stack": "--------------------------------------------------------------------------- ValueError Traceback (most recent call last) Cell In[7], line 1 ----> 1 interpreter.get_sender_receiver_effects()
> 
> File ~/.conda/envs/ncem_env/lib/python3.9/site-packages/ncem/interpretation/interpreter.py:912, in InterpreterInteraction.get_sender_receiver_effects(self, params_type, significance_threshold) 910 print(target.shape) 911 print(interactions.shape) --> 912 x_design = np.concatenate([target, interactions.squeeze()], axis=1) 913 ols = ols_fit(x_=x_design, y_=y) 914 params = ols.squeeze()
> 
> File <**array_function** internals>:200, in concatenate(*args, **kwargs)
> 
> ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 8 and the array at index 1 has size 64" }

Hi @ShuangWang1 did you figure this out?

**Comment by LiuJiamao521** [comment]
Hi, I encountered the same dimension mismatch error in `ncem.get_sender_receiver_effects()` (v0.15)  and post it on 
https://github.com/theislab/ncem/issues/172. This fix worked successfully in my case, and I hope it proves helpful for others facing this issue.
